name: Sync Org → Personal Repo

on:
  push:
    branches:
      - '**'    # triggers on any branch push in org repo

permissions:
  contents: write  # grant workflow permission to push to personal repo

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout org repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to personal repo
        env:
          GIT_PUSH_URL: https://${{ secrets.PERSONAL_PAT }}@github.com/achyu-dev/gh-actions-test-repo.git
        run: |
          git remote add personal "$GIT_PUSH_URL"
          git push personal --all
          git push personal --tags
