# .github/workflows/sync-from-org.yml
name: Sync from org repo → personal

on:
  repository_dispatch:
    types: [org-push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout personal repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: achyu-dev/gh-actions-test-repo
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Git user
        uses: fregante/setup-git-user@v2

      - name: Add upstream remote & fetch
        run: |
          git remote add upstream https://github.com/pesu-dev/gh-actions-test-repo.git
          git fetch upstream

      - name: Try merging upstream/main
        run: |
          git checkout main
          git merge upstream/main -m "Sync from upstream"
        continue-on-error: true

      - name: On conflict, force-reset
        if: failure()
        run: |
          git reset --hard upstream/main

      - name: Push to personal repo
        run: |
          git push origin main --force
